stages:
  - Image Build
  - Deployment
  - Restart Pods
  - Image Scan

include:
  - project: 'DSO/DASTScanner'
    file: '.gitlab-ci.yml'
  - remote: 'https://gitlab.com/prismacloud-public/shift-left/extension/-/raw/master/.pcs.gitlab-ci.yml'
  - local: './version.yml'

CopyDevImages:
  stage: Image Build
  tags:
    - qed-stg-runner
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - mkdir -p /workspace
    # HMS .NET5 image
    - echo "FROM ghcr.io/quanted/hms:dev" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_dotnet:$CI_COMMIT_REF_NAME
    # HMS django image
    - echo "FROM ghcr.io/quanted/hms_app:dev-kube" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_django:$CI_COMMIT_REF_NAME
    # HMS flask image
    - echo "FROM ghcr.io/quanted/hms_flask:dev-kube" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_flask:$CI_COMMIT_REF_NAME
    # HMS dask image
    - echo "FROM ghcr.io/quanted/hms-dask:main" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_dask:$CI_COMMIT_REF_NAME
    # HMS nginx image
    - echo "FROM ghcr.io/quanted/hms-nginx:dev-gl" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_nginx:$CI_COMMIT_REF_NAME
    # HMS mongo image
    - echo "FROM ghcr.io/quanted/hms-mongo:dev-gl" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_mongo:$CI_COMMIT_REF_NAME
  environment:
    name: stg
    url: http://qed.qed-stage.aws.epa.gov
    kubernetes:
      namespace: qed-45-stg

SetProdImages:
  stage: Image Build
  tags:
    - qed-stg-runner
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - mkdir -p /workspace
    # HMS .NET5 image
    - echo "FROM $CI_REGISTRY_IMAGE/hms_dotnet:dev-gl" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_dotnet:main-$PROD_VERSION
    # HMS django image
    - echo "FROM $CI_REGISTRY_IMAGE/hms_django:dev-gl" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_django:main-$PROD_VERSION
    # HMS flask image
    - echo "FROM $CI_REGISTRY_IMAGE/hms_flask:dev-gl" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_flask:main-$PROD_VERSION
    # HMS dask image
    - echo "FROM $CI_REGISTRY_IMAGE/hms_dask:dev-gl" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_dask:main-$PROD_VERSION
    # HMS nginx image
    - echo "FROM $CI_REGISTRY_IMAGE/hms_nginx:dev-gl" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_nginx:main-$PROD_VERSION
    # HMS mongo image
    - echo "FROM $CI_REGISTRY_IMAGE/hms_mongo:dev-gl" > /workspace/Dockerfile
    - /kaniko/executor --context=/workspace --destination=$CI_REGISTRY_IMAGE/hms_mongo:main-$PROD_VERSION
  environment:
    name: stg
    url: http://qed.qed-stage.aws.epa.gov
    kubernetes:
      namespace: qed-45-stg

LoadVolumeData:
  stage: Deployment
  tags:
    - qed-stg-runner
  when: manual
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --server="$KUBE_URL"
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --certificate-authority=$KUBE_CA_PEM_FILE --embed-certs=true
    - kubectl config set-credentials gitlab --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster="$KUBECTL_DEV_CLUSTER" --user=gitlab --namespace="$KUBE_NAMESPACE"
    - kubectl config use-context default
    - chmod 775 ./hms-volume-setup.sh
    - ./hms-volume-setup.sh
  environment:
    name: stg
    url: http://qed.qed-stage.aws.epa.gov
    kubernetes:
      namespace: qed-45-stg

ApplyManifests:
  stage: Deployment
  tags:
    - qed-stg-runner
  when: manual
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --server="$KUBE_URL"
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --certificate-authority=$KUBE_CA_PEM_FILE --embed-certs=true
    - kubectl config set-credentials gitlab --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster="$KUBECTL_DEV_CLUSTER" --user=gitlab --namespace="$KUBE_NAMESPACE"
    - kubectl config use-context default
    - kubectl apply -f k8s/
  environment:
    name: stg
    url: http://qed.qed-stage.aws.epa.gov
    kubernetes:
      namespace: qed-45-stg
      
DeleteManifests:
  stage: Deployment
  tags:
    - qed-stg-runner
  when: manual
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --server="$KUBE_URL"
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --certificate-authority=$KUBE_CA_PEM_FILE --embed-certs=true
    - kubectl config set-credentials gitlab --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster="$KUBECTL_DEV_CLUSTER" --user=gitlab --namespace="$KUBE_NAMESPACE"
    - kubectl config use-context default
    - kubectl delete -f k8s/
  environment:
    name: stg
    url: http://qed.qed-stage.aws.epa.gov
    kubernetes:
      namespace: qed-45-stg

ScaleDjango:
  stage: Restart Pods
  tags:
    - qed-stg-runner
  when: manual
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --server="$KUBE_URL"
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --certificate-authority=$KUBE_CA_PEM_FILE --embed-certs=true
    - kubectl config set-credentials gitlab --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster="$KUBECTL_DEV_CLUSTER" --user=gitlab --namespace="$KUBE_NAMESPACE"
    - kubectl config use-context default
    - kubectl scale deployment hms-django --replicas=0
    - kubectl scale deployment hms-django --replicas=1
  environment:
    name: stg
    url: http://qed.qed-stage.aws.epa.gov
    kubernetes:
      namespace: qed-45-stg

ScalePods:
  stage: Restart Pods
  tags:
    - qed-stg-runner
  when: manual
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --server="$KUBE_URL"
    - kubectl config set-cluster "$KUBECTL_DEV_CLUSTER" --certificate-authority=$KUBE_CA_PEM_FILE --embed-certs=true
    - kubectl config set-credentials gitlab --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster="$KUBECTL_DEV_CLUSTER" --user=gitlab --namespace="$KUBE_NAMESPACE"
    - kubectl config use-context default
    - kubectl scale deployment hms-django --replicas=0
    - kubectl scale deployment hms-django --replicas=1
    - kubectl scale deployment hms-flask --replicas=0
    - kubectl scale deployment hms-flask --replicas=1
    - kubectl scale deployment hms-dask-worker --replicas=0
    - kubectl scale deployment hms-dask-worker --replicas=3
    - kubectl scale deployment hms-dotnet --replicas=0
    - kubectl scale deployment hms-dotnet --replicas=1
    - kubectl scale deployment hms-nginx --replicas=0
    - kubectl scale deployment hms-nginx --replicas=1
  environment:
    name: stg
    url: http://qed.qed-stage.aws.epa.gov
    kubernetes:
      namespace: qed-45-stg

DotNetImageScan:
  stage: Image Scan
  extends:
    - .pcs_compute_scan
  tags:
    - twistcli
  when: manual
  allow_failure: false
  variables:
    prisma_cloud_compute_url: "https://prismacloud.gitlab-prod.aws.epa.gov"
    GIT_STRATEGY: clone
    prisma_cloud_scan_image: "registry.epa.gov/qed/hms_kube/hms_dotnet:dev-gl"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.epa.gov
    - docker pull $prisma_cloud_scan_image
    - ./image_scan.sh


DjangoImageScan:
  stage: Image Scan
  extends:
    - .pcs_compute_scan
  tags:
    - twistcli
  when: manual
  allow_failure: false
  variables:
    prisma_cloud_compute_url: "https://prismacloud.gitlab-prod.aws.epa.gov"
    GIT_STRATEGY: clone
    prisma_cloud_scan_image: "registry.epa.gov/qed/hms_kube/hms_django:dev-gl"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.epa.gov
    - docker pull $prisma_cloud_scan_image
    - ./image_scan.sh

FlaskImageScan:
  stage: Image Scan
  extends:
    - .pcs_compute_scan
  tags:
    - twistcli
  when: manual
  allow_failure: false
  variables:
    prisma_cloud_compute_url: "https://prismacloud.gitlab-prod.aws.epa.gov"
    GIT_STRATEGY: clone
    prisma_cloud_scan_image: "registry.epa.gov/qed/hms_kube/hms_flask:dev-gl"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.epa.gov
    - docker pull $prisma_cloud_scan_image
    - ./image_scan.sh

DaskImageScan:
  stage: Image Scan
  extends:
    - .pcs_compute_scan
  tags:
    - twistcli
  when: manual
  allow_failure: false
  variables:
    prisma_cloud_compute_url: "https://prismacloud.gitlab-prod.aws.epa.gov"
    GIT_STRATEGY: clone
    prisma_cloud_scan_image: "registry.epa.gov/qed/hms_kube/hms_dask:dev-gl"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.epa.gov
    - docker pull $prisma_cloud_scan_image
    - ./image_scan.sh

NginxImageScan:
  stage: Image Scan
  extends:
    - .pcs_compute_scan
  tags:
    - twistcli
  when: manual
  allow_failure: false
  variables:
    prisma_cloud_compute_url: "https://prismacloud.gitlab-prod.aws.epa.gov"
    GIT_STRATEGY: clone
    prisma_cloud_scan_image: "registry.epa.gov/qed/hms_kube/hms_nginx:dev-gl"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.epa.gov
    - docker pull $prisma_cloud_scan_image
    - ./image_scan.sh

MongoImageScan:
  stage: Image Scan
  extends:
    - .pcs_compute_scan
  tags:
    - twistcli
  when: manual
  allow_failure: false
  variables:
    prisma_cloud_compute_url: "https://prismacloud.gitlab-prod.aws.epa.gov"
    GIT_STRATEGY: clone
    prisma_cloud_scan_image: "registry.epa.gov/qed/hms_kube/hms_mongo:dev-gl"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.epa.gov
    - docker pull $prisma_cloud_scan_image
    - ./image_scan.sh
