apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: hms-dask-scheduler
  name: hms-dask-scheduler
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-dask-scheduler
  template:
    metadata:
      labels:
        app: hms-dask-scheduler
    spec:
      containers:
      - args:
        - dask-scheduler
        # - conda
        # - run
        # - -n
        # - pyenv
        # - --no-capture-output
        # - dask-scheduler
        image: ghcr.io/quanted/hms-dask:main
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8786
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8786
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        name: hms-dask-scheduler
        ports:
        - containerPort: 8786
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
      hostname: hms-dask-scheduler
      restartPolicy: Always
