apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: hms-dask-scheduler
  name: hms-dask-scheduler
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-dask-scheduler
  template:
    metadata:
      labels:
        app: hms-dask-scheduler
    spec:
      containers:
      - args:
        - dask-scheduler
        image: ghcr.io/quanted/hms_flask:dev-kube
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        name: hms-dask-scheduler
        ports:
        - containerPort: 8786
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
      hostname: hms-dask-scheduler
      restartPolicy: Always
