apiVersion: v1
kind: Service
metadata:
  name: hms-django
  namespace: qed-kube-scripts-79-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hms-django
  type: ClusterIP