apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hms-dask-worker
  name: hms-dask-worker
  namespace: hms-kube
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hms-dask-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hms-dask-worker
    spec:
      containers:
      - args:
        - conda
        - run
        - -n
        - pyenv
        - --no-capture-output
        - dask-worker
        - hms-dask-scheduler:8786
        image: registry.epa.gov/qed/hms_kube/hms_dask:dev-gl
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: hms-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
              - ls
              - /
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        name: hms-dask-worker
      hostname: hms-dask-worker
      restartPolicy: Always
      schedulerName: default-scheduler