apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hms-flask
  name: hms-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hms-flask
    spec:
      containers:
      - image: dbsmith88/hms-flask:dev-kube
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: hms-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        name: hms-flask
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler