apiVersion: v1
kind: Service
metadata:
  name: hms-nginx
  namespace: qed-kube-scripts-79-dev
spec:
  selector:
    app: hms-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 7777
      targetPort: 7777
      name: flask