apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hms-nginx
  name: hms-nginx
  namespace: qed-45-stg
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hms-nginx
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: hms-config
        image: registry.epa.gov/qed/hms_kube/hms_nginx:dev-gl
        imagePullPolicy: Always
        name: nginx
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
#         - containerPort: 443
        volumeMounts:
        - mountPath: /src/collected_static
          name: collected-static
      restartPolicy: Always
      imagePullSecrets:
        - name: glcr-auth
      volumes:
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
