apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hms-flask
  name: hms-flask
  namespace: hms-80-stg
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hms-flask
    spec:
      containers:
      - image: registry.epa.gov/qed/hms_kube/hms_flask:dev-gl
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: hms-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 10
        name: hms-flask
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: /src/hms-data
            name: hms-dotnet-appdata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: hms-dotnet-appdata
          persistentVolumeClaim:
            claimName: hms-dotnetcore-appdata-pvolume-claim