apiVersion: v1
kind: Service
metadata:
  name: hms-dotnet
  namespace: qed-kube-scripts-79-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hms-dotnet
  type: ClusterIP
