apiVersion: v1
kind: Service
metadata:
  name: hms-nginx
  namespace: default
spec:
  selector:
    app: hms-nginx
  # type: ClusterIP
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80
      name: http
    - protocol: TCP
      port: 7777
      targetPort: 7777
      name: flask
