apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hms-mongodb
  name: hms-mongodb
  namespace: qed-kube-dev
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: hms-mongodb
  serviceName: hms-mongodb
  template:
    metadata:
      labels:
        app: hms-mongodb
    spec:
      containers:
      - image: ghcr.io/quanted/hms-mongo:main
        imagePullPolicy: Always
        command: ['mongod', '--bind_ip_all']
        name: hms-mongodb
        readinessProbe:
          exec:
            command:
            - ls
            - /
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - ls
            - /
          initialDelaySeconds: 15
          periodSeconds: 30
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
          - mountPath: /data/db
            name: mongodb-pvolume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: mongodb-pvolume
          persistentVolumeClaim:
            claimName: mongodb-pvolume-claim1