apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hms-django
  name: hms-django
  namespace: hms-kube
    annotations:
      app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
      app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
      eks.amazonaws.com/compute-type: fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hms-django
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: hms-config
        image: registry.epa.gov/qed/hms_kube/hms_django:dev-gl
        imagePullPolicy: Always
        name: hms-django
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /src/hms_app/collected_static
          name: collected-static
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
