apiVersion: v1
kind: Service
metadata:
  name: hms-nginx
  namespace: qed-45-stg
spec:
  selector:
    app: hms-nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 7777
      targetPort: 7777
      name: flask
