apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hms-nginx
  name: hms-nginx
  namespace: qed-kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hms-nginx
    spec:
      containers:
      - image: ghcr.io/quanted/hms-nginx:dev-aws
        imagePullPolicy: Always
        name: nginx
        readinessProbe:
          tcpSocket:
            port: 8008
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8008
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8008
        - containerPort: 7777
        volumeMounts:
        - mountPath: /src/collected_static
          name: collected-static
      restartPolicy: Always
      volumes:
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
