apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hms-dotnetcore
  name: hms-dotnetcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-dotnetcore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hms-dotnetcore
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: hms-config
        image: dbsmith88/hms_dotnetcore:dev
        imagePullPolicy: Always
        name: hms-dotnetcore
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
          - containerPort: 80
            protocol: TCP
        volumeMounts:
        - mountPath: /app/App_Data
          name: hms-dotnetcore-appdata
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      imagePullSecrets:
        - name: glcr-auth
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: hms-dotnetcore-appdata
          hostPath:
            path: /D//data/hms/app-data
#       - name: hms-dotnetcore-appdata
#         persistentVolumeClaim:
#           claimName: hms-dotnetcore-appdata-pvolume-claim1
