apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hms-mongodb
  name: hms-mongodb
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: hms-mongodb
  serviceName: hms-mongodb
  template:
    metadata:
      labels:
        app: hms-mongodb
    spec:
      containers:
      - image: mongo:latest
#      - image: ghcr.io/quanted/hms-mongo:main
#      - image: hms-mongo-test-05
        imagePullPolicy: Always
#        resources:
#          requests:
#            memory: "512Mi"
#            cpu: "500m"
#          limits:
#            memory: "1Gi"
#            cpu: "1000m"
        name: hms-mongodb
#        readinessProbe:
#          exec:
#            command:
#            - ls
#            - /
#          initialDelaySeconds: 5
#          periodSeconds: 10
#        livenessProbe:
#          exec:
#            command:
#            - ls
#            - /
#          initialDelaySeconds: 15
#          periodSeconds: 30
        ports:
        - containerPort: 27017
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
