apiVersion: v1
kind: Service
metadata:
  name: hms-nginx
spec:
  type: NodePort
  selector:
    app: hms-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
      name: http
    - protocol: TCP
      port: 7777
      targetPort: 7777
      name: flask