apiVersion: v1
kind: Service
metadata:
  name: hms-dask-scheduler
  namespace: hms-80-stg
spec:
  ports:
  - name: dask1
    port: 8786
    protocol: TCP
    targetPort: 8786
  - name: dask2
    port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    app: hms-dask-scheduler
  type: ClusterIP