apiVersion: v1
kind: Service
metadata:
  name: hms-dotnet
  namespace: qed-kube-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hms-dotnet
  type: ClusterIP
