piVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hms-flask
  name: hms-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hms-flask
    spec:
      containers:
      - image: dbsmith88/hms-flask:dev-kube
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: hms-config
#        readinessProbe:
#          tcpSocket:
#            port: 8080
#          initialDelaySeconds: 5
#          periodSeconds: 10
#          timeoutSeconds: 10
#        livenessProbe:
#          tcpSocket:
#            port: 8080
#          initialDelaySeconds: 15
#          periodSeconds: 30
#          timeoutSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        name: hms-flask
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /src/app-data
          name: app-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-pvolume-claim1
#      volumes:
              #- name: app-data
              # hostPath:
              #path: /host/app-data
            #- name: flask-code
            #hostPath:
            #path: /host/flask-code