apiVersion: v1
kind: Service
metadata:
  name: hms-mongodb
  namespace: qed-kube-dev
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: hms-mongodb
  type: ClusterIP